# Ref: https://goreleaser.com/customization/builds/
builds:
  # Ref: https://goreleaser.com/errors/no-main/#if-you-are-building-a-library
  - skip: true

snapshot:
  version_template: "{{ incpatch .Version }}-alpha"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  name_template: 'v{{ .Version }}'
